import PageLayout from "@/components/layout/PageLayout";
import ShipmentDetailsPage from "@/components/pages/orders/ShipmentDetailsPage";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/_authenticated/orders/$id/")({
  component: RouteComponent,
});
const shipmentData = {
  pickup_info: {
    pickup_state: "Maharashtra",
    pickup_address: "Indiranagar ",
    email: "deepanshu.kartikey@pyck.in",
    pickup_time: "2025-03-01T19:00:00Z",
    pickup_pincode: "400077",
    pickup_city: "Mumbai",
    tin: "120349483",
    pickup_name: "TS Surface",
    pickup_country: "India",
    pickup_phone: "9917344496",
    pickup_lat: 10.01,
    pickup_long: 10.0,
    pickup_organisation: "Nykaa",
    pickup_district: "Mumbai",
    pickup_landmark: "Near XYZ Towers",
    pickup_address_type: "RESIDENTIAL",
  },
  drop_info: {
    drop_address: "F-68 third floor kalkaji New Delhi ",
    drop_phone: "9717732407",
    drop_country: "IN",
    drop_state: "DELHI",
    drop_pincode: "400024",
    drop_city: "Delhi",
    drop_name: "Prashant",
    drop_email: "support@clickpost.in",
    drop_lat: 10.01,
    drop_long: 10.0,
    drop_organisation: "Nykaa",
    drop_district: "Delhi",
    drop_landmark: "Near XYZ Towers",
    drop_start_time: "2025-03-05T10:02:33+0530",
    drop_end_time: "2025-03-05T12:02:33+0530",
    drop_address_type: "RESIDENTIAL",
    drop_vendor_code: "",
    location_type: "What3Words",
    location_value: "stickler.leaky.workers",
  },
  shipment_details: {
    order_type: "COD",
    invoice_value: 200,
    invoice_number: "INV123",
    invoice_date: "2025-02-27",
    reference_number: "test-reference-number-2",
    length: 10,
    breadth: 10,
    weight: 100,
    height: 12,
    cod_value: 200.45,
    courier_partner: 207,
    account_code: "test",
    order_id: "test123",
    delivery_type: "FORWARD",
    items: [
      {
        product_url: "<Product Page Url>",
        price: 200.78,
        description: "item1",
        quantity: 1,
        weight: 500.25,
        sku: "XYZ1",
        final_amount_paid: "200.00",
        store_credits_used: "50.50",
        product_id: "4817825955902",
        variant_id: "32783884976190",
        additional: {
          length: 10,
          height: 10,
          breadth: 10,
          weight: 100,
          images: "http://sample-file1.jpg,http://sample-file2.jpg",
          return_days: 2,
          cat: "Footwear",
          manufacture_country_code: "IN",
          manufacture_country: "India",
          exchange_days: 5,
          color: "dark blue",
          sub_category: "T-Shirt",
          size: "XL",
          brand: "Puma",
          special_instructions: "Handle with care",
          imei: "12345678910111",
          ean: "EAN111111",
          product_url: "https://www.clickpost.ai",
          return_reason: "Some test reason",
        },
      },
    ],
  },
  additional: {
    label: true,
    return_info: {
      pincode: "110019",
      address: "Test Address top floor kalkaji NewDelhi ",
      state: "DELHI",
      phone: "8080808080",
      name: "Deepanshu",
      city: "DELHI",
      country: "IN",
      lat: 25.1414664,
      long: 55.255369,
      district: "Delhi",
      landmark: "Near XYZ Towers",
      email: "deepanshu.kartikey@pyck.in",
    },
    async: false,
    gst_number: "21313",
    channel_name: "Testchannel",
    order_date: "2023-11-05T00:00:00+00:00",
    enable_whatsapp: false,
    is_fragile: true,
    is_dangerous: true,
    zone: "XYZ Locality",
    max_edd: 10,
    min_edd: 5,
    invoice_base_64: "XYZ",
    is_multi_seller: false,
    vendor_code: "",
    store_code: "abc",
    user_defined_field_array: [
      {
        name: "udf_1",
        type: "String",
        value: "",
      },
      {
        name: "udf_2",
        type: "String",
        value: "",
      },
      {
        name: "udf_3",
        type: "String",
        value: "",
      },
      {
        name: "udf_4",
        type: "String",
        value: "",
      },
    ],
    estimated_delivery_date: "2023-12-05",
  },
  gst_info: {
    seller_gstin: "1234",
    taxable_value: 100.55,
    ewaybill_serial_number: "2345677",
    is_seller_registered_under_gst: false,
    sgst_tax_rate: 100,
    place_of_supply: "DELHI",
    gst_discount: 0,
    hsn_code: "1234",
    sgst_amount: 100,
    enterprise_gstin: "13",
    gst_total_tax: 100,
    igst_amount: 100,
    cgst_amount: 200,
    gst_tax_base: 200,
    consignee_gstin: "1233",
    igst_tax_rate: 100,
    invoice_reference: "1234",
    cgst_tax_rate: 100,
    invoice_number: "12345",
    invoice_date: "2024-01-22",
    invoice_value: 1000,
    seller_name: "",
    seller_address: "",
    seller_state: "",
    seller_pincode: "",
  },
};

function RouteComponent() {
  return (
    <PageLayout
      items={[
        { title: "Home", href: "/home" },
        { title: "Orders", href: "/orders" },
        { title: "Order Details" },
      ]}
    >
      <ShipmentDetailsPage data={shipmentData} />
    </PageLayout>
  );
}
