/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as ToolsIndexImport } from './routes/tools/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as AddOrdersIndexImport } from './routes/add-orders/index'
import { Route as ToolsReportsRouteImport } from './routes/tools/reports/route'
import { Route as ToolsRateCardRouteImport } from './routes/tools/rate-card/route'
import { Route as ToolsRateCalculatorRouteImport } from './routes/tools/rate-calculator/route'
import { Route as ToolsActivityLogsIndexImport } from './routes/tools/activity-logs/index'
import { Route as SettingsUsersIndexImport } from './routes/settings/users/index'
import { Route as SettingsTaxConfigurationIndexImport } from './routes/settings/tax-configuration/index'
import { Route as SettingsPickupLocationsIndexImport } from './routes/settings/pickup-locations/index'
import { Route as SettingsInvoiceTemplatesIndexImport } from './routes/settings/invoice-templates/index'
import { Route as SettingsCompanyDetailsIndexImport } from './routes/settings/company-details/index'
import { Route as SettingsBankDetailsIndexImport } from './routes/settings/bank-details/index'
import { Route as SettingsApiSetupsIndexImport } from './routes/settings/api-setups/index'
import { Route as AddOrdersLayoutSingleOrderImport } from './routes/add-orders/_layout/single-order'
import { Route as ToolsReportsDownloadReportsRouteImport } from './routes/tools/reports/download-reports/route'
import { Route as ToolsReportsReportsSchedulerIndexImport } from './routes/tools/reports/reports-scheduler/index'
import { Route as ToolsRateCardReverseIndexImport } from './routes/tools/rate-card/reverse/index'
import { Route as ToolsRateCardForwardIndexImport } from './routes/tools/rate-card/forward/index'
import { Route as ToolsRateCardDocumentIndexImport } from './routes/tools/rate-card/document/index'
import { Route as ToolsRateCalculatorInternationalIndexImport } from './routes/tools/rate-calculator/international/index'
import { Route as ToolsRateCalculatorDomesticIndexImport } from './routes/tools/rate-calculator/domestic/index'
import { Route as ToolsReportsDownloadReportsInstantReportsIndexImport } from './routes/tools/reports/download-reports/instant-reports/index'

// Create Virtual Routes

const ToolsReportsDownloadReportsScheduledReportsIndexLazyImport =
  createFileRoute('/tools/reports/download-reports/scheduled-reports/')()

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsIndexRoute = ToolsIndexImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AddOrdersIndexRoute = AddOrdersIndexImport.update({
  id: '/add-orders/',
  path: '/add-orders/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsReportsRouteRoute = ToolsReportsRouteImport.update({
  id: '/tools/reports',
  path: '/tools/reports',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRateCardRouteRoute = ToolsRateCardRouteImport.update({
  id: '/tools/rate-card',
  path: '/tools/rate-card',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRateCalculatorRouteRoute = ToolsRateCalculatorRouteImport.update({
  id: '/tools/rate-calculator',
  path: '/tools/rate-calculator',
  getParentRoute: () => rootRoute,
} as any)

const ToolsActivityLogsIndexRoute = ToolsActivityLogsIndexImport.update({
  id: '/tools/activity-logs/',
  path: '/tools/activity-logs/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsUsersIndexRoute = SettingsUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsTaxConfigurationIndexRoute =
  SettingsTaxConfigurationIndexImport.update({
    id: '/tax-configuration/',
    path: '/tax-configuration/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

const SettingsPickupLocationsIndexRoute =
  SettingsPickupLocationsIndexImport.update({
    id: '/pickup-locations/',
    path: '/pickup-locations/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

const SettingsInvoiceTemplatesIndexRoute =
  SettingsInvoiceTemplatesIndexImport.update({
    id: '/invoice-templates/',
    path: '/invoice-templates/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

const SettingsCompanyDetailsIndexRoute =
  SettingsCompanyDetailsIndexImport.update({
    id: '/company-details/',
    path: '/company-details/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

const SettingsBankDetailsIndexRoute = SettingsBankDetailsIndexImport.update({
  id: '/bank-details/',
  path: '/bank-details/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsApiSetupsIndexRoute = SettingsApiSetupsIndexImport.update({
  id: '/api-setups/',
  path: '/api-setups/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const AddOrdersLayoutSingleOrderRoute = AddOrdersLayoutSingleOrderImport.update(
  {
    id: '/add-orders/_layout/single-order',
    path: '/add-orders/single-order',
    getParentRoute: () => rootRoute,
  } as any,
)

const ToolsReportsDownloadReportsRouteRoute =
  ToolsReportsDownloadReportsRouteImport.update({
    id: '/download-reports',
    path: '/download-reports',
    getParentRoute: () => ToolsReportsRouteRoute,
  } as any)

const ToolsReportsReportsSchedulerIndexRoute =
  ToolsReportsReportsSchedulerIndexImport.update({
    id: '/reports-scheduler/',
    path: '/reports-scheduler/',
    getParentRoute: () => ToolsReportsRouteRoute,
  } as any)

const ToolsRateCardReverseIndexRoute = ToolsRateCardReverseIndexImport.update({
  id: '/reverse/',
  path: '/reverse/',
  getParentRoute: () => ToolsRateCardRouteRoute,
} as any)

const ToolsRateCardForwardIndexRoute = ToolsRateCardForwardIndexImport.update({
  id: '/forward/',
  path: '/forward/',
  getParentRoute: () => ToolsRateCardRouteRoute,
} as any)

const ToolsRateCardDocumentIndexRoute = ToolsRateCardDocumentIndexImport.update(
  {
    id: '/document/',
    path: '/document/',
    getParentRoute: () => ToolsRateCardRouteRoute,
  } as any,
)

const ToolsRateCalculatorInternationalIndexRoute =
  ToolsRateCalculatorInternationalIndexImport.update({
    id: '/international/',
    path: '/international/',
    getParentRoute: () => ToolsRateCalculatorRouteRoute,
  } as any)

const ToolsRateCalculatorDomesticIndexRoute =
  ToolsRateCalculatorDomesticIndexImport.update({
    id: '/domestic/',
    path: '/domestic/',
    getParentRoute: () => ToolsRateCalculatorRouteRoute,
  } as any)

const ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute =
  ToolsReportsDownloadReportsScheduledReportsIndexLazyImport.update({
    id: '/scheduled-reports/',
    path: '/scheduled-reports/',
    getParentRoute: () => ToolsReportsDownloadReportsRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/tools/reports/download-reports/scheduled-reports/index.lazy'
    ).then((d) => d.Route),
  )

const ToolsReportsDownloadReportsInstantReportsIndexRoute =
  ToolsReportsDownloadReportsInstantReportsIndexImport.update({
    id: '/instant-reports/',
    path: '/instant-reports/',
    getParentRoute: () => ToolsReportsDownloadReportsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/tools/rate-calculator': {
      id: '/tools/rate-calculator'
      path: '/tools/rate-calculator'
      fullPath: '/tools/rate-calculator'
      preLoaderRoute: typeof ToolsRateCalculatorRouteImport
      parentRoute: typeof rootRoute
    }
    '/tools/rate-card': {
      id: '/tools/rate-card'
      path: '/tools/rate-card'
      fullPath: '/tools/rate-card'
      preLoaderRoute: typeof ToolsRateCardRouteImport
      parentRoute: typeof rootRoute
    }
    '/tools/reports': {
      id: '/tools/reports'
      path: '/tools/reports'
      fullPath: '/tools/reports'
      preLoaderRoute: typeof ToolsReportsRouteImport
      parentRoute: typeof rootRoute
    }
    '/add-orders/': {
      id: '/add-orders/'
      path: '/add-orders'
      fullPath: '/add-orders'
      preLoaderRoute: typeof AddOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/reports/download-reports': {
      id: '/tools/reports/download-reports'
      path: '/download-reports'
      fullPath: '/tools/reports/download-reports'
      preLoaderRoute: typeof ToolsReportsDownloadReportsRouteImport
      parentRoute: typeof ToolsReportsRouteImport
    }
    '/add-orders/_layout/single-order': {
      id: '/add-orders/_layout/single-order'
      path: '/add-orders/single-order'
      fullPath: '/add-orders/single-order'
      preLoaderRoute: typeof AddOrdersLayoutSingleOrderImport
      parentRoute: typeof rootRoute
    }
    '/settings/api-setups/': {
      id: '/settings/api-setups/'
      path: '/api-setups'
      fullPath: '/settings/api-setups'
      preLoaderRoute: typeof SettingsApiSetupsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/bank-details/': {
      id: '/settings/bank-details/'
      path: '/bank-details'
      fullPath: '/settings/bank-details'
      preLoaderRoute: typeof SettingsBankDetailsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/company-details/': {
      id: '/settings/company-details/'
      path: '/company-details'
      fullPath: '/settings/company-details'
      preLoaderRoute: typeof SettingsCompanyDetailsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/invoice-templates/': {
      id: '/settings/invoice-templates/'
      path: '/invoice-templates'
      fullPath: '/settings/invoice-templates'
      preLoaderRoute: typeof SettingsInvoiceTemplatesIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/pickup-locations/': {
      id: '/settings/pickup-locations/'
      path: '/pickup-locations'
      fullPath: '/settings/pickup-locations'
      preLoaderRoute: typeof SettingsPickupLocationsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/tax-configuration/': {
      id: '/settings/tax-configuration/'
      path: '/tax-configuration'
      fullPath: '/settings/tax-configuration'
      preLoaderRoute: typeof SettingsTaxConfigurationIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/users/': {
      id: '/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/tools/activity-logs/': {
      id: '/tools/activity-logs/'
      path: '/tools/activity-logs'
      fullPath: '/tools/activity-logs'
      preLoaderRoute: typeof ToolsActivityLogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/rate-calculator/domestic/': {
      id: '/tools/rate-calculator/domestic/'
      path: '/domestic'
      fullPath: '/tools/rate-calculator/domestic'
      preLoaderRoute: typeof ToolsRateCalculatorDomesticIndexImport
      parentRoute: typeof ToolsRateCalculatorRouteImport
    }
    '/tools/rate-calculator/international/': {
      id: '/tools/rate-calculator/international/'
      path: '/international'
      fullPath: '/tools/rate-calculator/international'
      preLoaderRoute: typeof ToolsRateCalculatorInternationalIndexImport
      parentRoute: typeof ToolsRateCalculatorRouteImport
    }
    '/tools/rate-card/document/': {
      id: '/tools/rate-card/document/'
      path: '/document'
      fullPath: '/tools/rate-card/document'
      preLoaderRoute: typeof ToolsRateCardDocumentIndexImport
      parentRoute: typeof ToolsRateCardRouteImport
    }
    '/tools/rate-card/forward/': {
      id: '/tools/rate-card/forward/'
      path: '/forward'
      fullPath: '/tools/rate-card/forward'
      preLoaderRoute: typeof ToolsRateCardForwardIndexImport
      parentRoute: typeof ToolsRateCardRouteImport
    }
    '/tools/rate-card/reverse/': {
      id: '/tools/rate-card/reverse/'
      path: '/reverse'
      fullPath: '/tools/rate-card/reverse'
      preLoaderRoute: typeof ToolsRateCardReverseIndexImport
      parentRoute: typeof ToolsRateCardRouteImport
    }
    '/tools/reports/reports-scheduler/': {
      id: '/tools/reports/reports-scheduler/'
      path: '/reports-scheduler'
      fullPath: '/tools/reports/reports-scheduler'
      preLoaderRoute: typeof ToolsReportsReportsSchedulerIndexImport
      parentRoute: typeof ToolsReportsRouteImport
    }
    '/tools/reports/download-reports/instant-reports/': {
      id: '/tools/reports/download-reports/instant-reports/'
      path: '/instant-reports'
      fullPath: '/tools/reports/download-reports/instant-reports'
      preLoaderRoute: typeof ToolsReportsDownloadReportsInstantReportsIndexImport
      parentRoute: typeof ToolsReportsDownloadReportsRouteImport
    }
    '/tools/reports/download-reports/scheduled-reports/': {
      id: '/tools/reports/download-reports/scheduled-reports/'
      path: '/scheduled-reports'
      fullPath: '/tools/reports/download-reports/scheduled-reports'
      preLoaderRoute: typeof ToolsReportsDownloadReportsScheduledReportsIndexLazyImport
      parentRoute: typeof ToolsReportsDownloadReportsRouteImport
    }
  }
}

// Create and export the route tree

interface SettingsRouteRouteChildren {
  SettingsApiSetupsIndexRoute: typeof SettingsApiSetupsIndexRoute
  SettingsBankDetailsIndexRoute: typeof SettingsBankDetailsIndexRoute
  SettingsCompanyDetailsIndexRoute: typeof SettingsCompanyDetailsIndexRoute
  SettingsInvoiceTemplatesIndexRoute: typeof SettingsInvoiceTemplatesIndexRoute
  SettingsPickupLocationsIndexRoute: typeof SettingsPickupLocationsIndexRoute
  SettingsTaxConfigurationIndexRoute: typeof SettingsTaxConfigurationIndexRoute
  SettingsUsersIndexRoute: typeof SettingsUsersIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsApiSetupsIndexRoute: SettingsApiSetupsIndexRoute,
  SettingsBankDetailsIndexRoute: SettingsBankDetailsIndexRoute,
  SettingsCompanyDetailsIndexRoute: SettingsCompanyDetailsIndexRoute,
  SettingsInvoiceTemplatesIndexRoute: SettingsInvoiceTemplatesIndexRoute,
  SettingsPickupLocationsIndexRoute: SettingsPickupLocationsIndexRoute,
  SettingsTaxConfigurationIndexRoute: SettingsTaxConfigurationIndexRoute,
  SettingsUsersIndexRoute: SettingsUsersIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ToolsRateCalculatorRouteRouteChildren {
  ToolsRateCalculatorDomesticIndexRoute: typeof ToolsRateCalculatorDomesticIndexRoute
  ToolsRateCalculatorInternationalIndexRoute: typeof ToolsRateCalculatorInternationalIndexRoute
}

const ToolsRateCalculatorRouteRouteChildren: ToolsRateCalculatorRouteRouteChildren =
  {
    ToolsRateCalculatorDomesticIndexRoute:
      ToolsRateCalculatorDomesticIndexRoute,
    ToolsRateCalculatorInternationalIndexRoute:
      ToolsRateCalculatorInternationalIndexRoute,
  }

const ToolsRateCalculatorRouteRouteWithChildren =
  ToolsRateCalculatorRouteRoute._addFileChildren(
    ToolsRateCalculatorRouteRouteChildren,
  )

interface ToolsRateCardRouteRouteChildren {
  ToolsRateCardDocumentIndexRoute: typeof ToolsRateCardDocumentIndexRoute
  ToolsRateCardForwardIndexRoute: typeof ToolsRateCardForwardIndexRoute
  ToolsRateCardReverseIndexRoute: typeof ToolsRateCardReverseIndexRoute
}

const ToolsRateCardRouteRouteChildren: ToolsRateCardRouteRouteChildren = {
  ToolsRateCardDocumentIndexRoute: ToolsRateCardDocumentIndexRoute,
  ToolsRateCardForwardIndexRoute: ToolsRateCardForwardIndexRoute,
  ToolsRateCardReverseIndexRoute: ToolsRateCardReverseIndexRoute,
}

const ToolsRateCardRouteRouteWithChildren =
  ToolsRateCardRouteRoute._addFileChildren(ToolsRateCardRouteRouteChildren)

interface ToolsReportsDownloadReportsRouteRouteChildren {
  ToolsReportsDownloadReportsInstantReportsIndexRoute: typeof ToolsReportsDownloadReportsInstantReportsIndexRoute
  ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute: typeof ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

const ToolsReportsDownloadReportsRouteRouteChildren: ToolsReportsDownloadReportsRouteRouteChildren =
  {
    ToolsReportsDownloadReportsInstantReportsIndexRoute:
      ToolsReportsDownloadReportsInstantReportsIndexRoute,
    ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute:
      ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute,
  }

const ToolsReportsDownloadReportsRouteRouteWithChildren =
  ToolsReportsDownloadReportsRouteRoute._addFileChildren(
    ToolsReportsDownloadReportsRouteRouteChildren,
  )

interface ToolsReportsRouteRouteChildren {
  ToolsReportsDownloadReportsRouteRoute: typeof ToolsReportsDownloadReportsRouteRouteWithChildren
  ToolsReportsReportsSchedulerIndexRoute: typeof ToolsReportsReportsSchedulerIndexRoute
}

const ToolsReportsRouteRouteChildren: ToolsReportsRouteRouteChildren = {
  ToolsReportsDownloadReportsRouteRoute:
    ToolsReportsDownloadReportsRouteRouteWithChildren,
  ToolsReportsReportsSchedulerIndexRoute:
    ToolsReportsReportsSchedulerIndexRoute,
}

const ToolsReportsRouteRouteWithChildren =
  ToolsReportsRouteRoute._addFileChildren(ToolsReportsRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools/rate-calculator': typeof ToolsRateCalculatorRouteRouteWithChildren
  '/tools/rate-card': typeof ToolsRateCardRouteRouteWithChildren
  '/tools/reports': typeof ToolsReportsRouteRouteWithChildren
  '/add-orders': typeof AddOrdersIndexRoute
  '/home': typeof HomeIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/reports/download-reports': typeof ToolsReportsDownloadReportsRouteRouteWithChildren
  '/add-orders/single-order': typeof AddOrdersLayoutSingleOrderRoute
  '/settings/api-setups': typeof SettingsApiSetupsIndexRoute
  '/settings/bank-details': typeof SettingsBankDetailsIndexRoute
  '/settings/company-details': typeof SettingsCompanyDetailsIndexRoute
  '/settings/invoice-templates': typeof SettingsInvoiceTemplatesIndexRoute
  '/settings/pickup-locations': typeof SettingsPickupLocationsIndexRoute
  '/settings/tax-configuration': typeof SettingsTaxConfigurationIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
  '/tools/activity-logs': typeof ToolsActivityLogsIndexRoute
  '/tools/rate-calculator/domestic': typeof ToolsRateCalculatorDomesticIndexRoute
  '/tools/rate-calculator/international': typeof ToolsRateCalculatorInternationalIndexRoute
  '/tools/rate-card/document': typeof ToolsRateCardDocumentIndexRoute
  '/tools/rate-card/forward': typeof ToolsRateCardForwardIndexRoute
  '/tools/rate-card/reverse': typeof ToolsRateCardReverseIndexRoute
  '/tools/reports/reports-scheduler': typeof ToolsReportsReportsSchedulerIndexRoute
  '/tools/reports/download-reports/instant-reports': typeof ToolsReportsDownloadReportsInstantReportsIndexRoute
  '/tools/reports/download-reports/scheduled-reports': typeof ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools/rate-calculator': typeof ToolsRateCalculatorRouteRouteWithChildren
  '/tools/rate-card': typeof ToolsRateCardRouteRouteWithChildren
  '/tools/reports': typeof ToolsReportsRouteRouteWithChildren
  '/add-orders': typeof AddOrdersIndexRoute
  '/home': typeof HomeIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/reports/download-reports': typeof ToolsReportsDownloadReportsRouteRouteWithChildren
  '/add-orders/single-order': typeof AddOrdersLayoutSingleOrderRoute
  '/settings/api-setups': typeof SettingsApiSetupsIndexRoute
  '/settings/bank-details': typeof SettingsBankDetailsIndexRoute
  '/settings/company-details': typeof SettingsCompanyDetailsIndexRoute
  '/settings/invoice-templates': typeof SettingsInvoiceTemplatesIndexRoute
  '/settings/pickup-locations': typeof SettingsPickupLocationsIndexRoute
  '/settings/tax-configuration': typeof SettingsTaxConfigurationIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
  '/tools/activity-logs': typeof ToolsActivityLogsIndexRoute
  '/tools/rate-calculator/domestic': typeof ToolsRateCalculatorDomesticIndexRoute
  '/tools/rate-calculator/international': typeof ToolsRateCalculatorInternationalIndexRoute
  '/tools/rate-card/document': typeof ToolsRateCardDocumentIndexRoute
  '/tools/rate-card/forward': typeof ToolsRateCardForwardIndexRoute
  '/tools/rate-card/reverse': typeof ToolsRateCardReverseIndexRoute
  '/tools/reports/reports-scheduler': typeof ToolsReportsReportsSchedulerIndexRoute
  '/tools/reports/download-reports/instant-reports': typeof ToolsReportsDownloadReportsInstantReportsIndexRoute
  '/tools/reports/download-reports/scheduled-reports': typeof ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools/rate-calculator': typeof ToolsRateCalculatorRouteRouteWithChildren
  '/tools/rate-card': typeof ToolsRateCardRouteRouteWithChildren
  '/tools/reports': typeof ToolsReportsRouteRouteWithChildren
  '/add-orders/': typeof AddOrdersIndexRoute
  '/home/': typeof HomeIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/reports/download-reports': typeof ToolsReportsDownloadReportsRouteRouteWithChildren
  '/add-orders/_layout/single-order': typeof AddOrdersLayoutSingleOrderRoute
  '/settings/api-setups/': typeof SettingsApiSetupsIndexRoute
  '/settings/bank-details/': typeof SettingsBankDetailsIndexRoute
  '/settings/company-details/': typeof SettingsCompanyDetailsIndexRoute
  '/settings/invoice-templates/': typeof SettingsInvoiceTemplatesIndexRoute
  '/settings/pickup-locations/': typeof SettingsPickupLocationsIndexRoute
  '/settings/tax-configuration/': typeof SettingsTaxConfigurationIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
  '/tools/activity-logs/': typeof ToolsActivityLogsIndexRoute
  '/tools/rate-calculator/domestic/': typeof ToolsRateCalculatorDomesticIndexRoute
  '/tools/rate-calculator/international/': typeof ToolsRateCalculatorInternationalIndexRoute
  '/tools/rate-card/document/': typeof ToolsRateCardDocumentIndexRoute
  '/tools/rate-card/forward/': typeof ToolsRateCardForwardIndexRoute
  '/tools/rate-card/reverse/': typeof ToolsRateCardReverseIndexRoute
  '/tools/reports/reports-scheduler/': typeof ToolsReportsReportsSchedulerIndexRoute
  '/tools/reports/download-reports/instant-reports/': typeof ToolsReportsDownloadReportsInstantReportsIndexRoute
  '/tools/reports/download-reports/scheduled-reports/': typeof ToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/tools/rate-calculator'
    | '/tools/rate-card'
    | '/tools/reports'
    | '/add-orders'
    | '/home'
    | '/tools'
    | '/tools/reports/download-reports'
    | '/add-orders/single-order'
    | '/settings/api-setups'
    | '/settings/bank-details'
    | '/settings/company-details'
    | '/settings/invoice-templates'
    | '/settings/pickup-locations'
    | '/settings/tax-configuration'
    | '/settings/users'
    | '/tools/activity-logs'
    | '/tools/rate-calculator/domestic'
    | '/tools/rate-calculator/international'
    | '/tools/rate-card/document'
    | '/tools/rate-card/forward'
    | '/tools/rate-card/reverse'
    | '/tools/reports/reports-scheduler'
    | '/tools/reports/download-reports/instant-reports'
    | '/tools/reports/download-reports/scheduled-reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/tools/rate-calculator'
    | '/tools/rate-card'
    | '/tools/reports'
    | '/add-orders'
    | '/home'
    | '/tools'
    | '/tools/reports/download-reports'
    | '/add-orders/single-order'
    | '/settings/api-setups'
    | '/settings/bank-details'
    | '/settings/company-details'
    | '/settings/invoice-templates'
    | '/settings/pickup-locations'
    | '/settings/tax-configuration'
    | '/settings/users'
    | '/tools/activity-logs'
    | '/tools/rate-calculator/domestic'
    | '/tools/rate-calculator/international'
    | '/tools/rate-card/document'
    | '/tools/rate-card/forward'
    | '/tools/rate-card/reverse'
    | '/tools/reports/reports-scheduler'
    | '/tools/reports/download-reports/instant-reports'
    | '/tools/reports/download-reports/scheduled-reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/tools/rate-calculator'
    | '/tools/rate-card'
    | '/tools/reports'
    | '/add-orders/'
    | '/home/'
    | '/tools/'
    | '/tools/reports/download-reports'
    | '/add-orders/_layout/single-order'
    | '/settings/api-setups/'
    | '/settings/bank-details/'
    | '/settings/company-details/'
    | '/settings/invoice-templates/'
    | '/settings/pickup-locations/'
    | '/settings/tax-configuration/'
    | '/settings/users/'
    | '/tools/activity-logs/'
    | '/tools/rate-calculator/domestic/'
    | '/tools/rate-calculator/international/'
    | '/tools/rate-card/document/'
    | '/tools/rate-card/forward/'
    | '/tools/rate-card/reverse/'
    | '/tools/reports/reports-scheduler/'
    | '/tools/reports/download-reports/instant-reports/'
    | '/tools/reports/download-reports/scheduled-reports/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ToolsRateCalculatorRouteRoute: typeof ToolsRateCalculatorRouteRouteWithChildren
  ToolsRateCardRouteRoute: typeof ToolsRateCardRouteRouteWithChildren
  ToolsReportsRouteRoute: typeof ToolsReportsRouteRouteWithChildren
  AddOrdersIndexRoute: typeof AddOrdersIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  AddOrdersLayoutSingleOrderRoute: typeof AddOrdersLayoutSingleOrderRoute
  ToolsActivityLogsIndexRoute: typeof ToolsActivityLogsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ToolsRateCalculatorRouteRoute: ToolsRateCalculatorRouteRouteWithChildren,
  ToolsRateCardRouteRoute: ToolsRateCardRouteRouteWithChildren,
  ToolsReportsRouteRoute: ToolsReportsRouteRouteWithChildren,
  AddOrdersIndexRoute: AddOrdersIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  AddOrdersLayoutSingleOrderRoute: AddOrdersLayoutSingleOrderRoute,
  ToolsActivityLogsIndexRoute: ToolsActivityLogsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/dashboard",
        "/settings",
        "/tools/rate-calculator",
        "/tools/rate-card",
        "/tools/reports",
        "/add-orders/",
        "/home/",
        "/tools/",
        "/add-orders/_layout/single-order",
        "/tools/activity-logs/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.jsx"
    },
    "/settings": {
      "filePath": "settings/route.jsx",
      "children": [
        "/settings/api-setups/",
        "/settings/bank-details/",
        "/settings/company-details/",
        "/settings/invoice-templates/",
        "/settings/pickup-locations/",
        "/settings/tax-configuration/",
        "/settings/users/"
      ]
    },
    "/tools/rate-calculator": {
      "filePath": "tools/rate-calculator/route.jsx",
      "children": [
        "/tools/rate-calculator/domestic/",
        "/tools/rate-calculator/international/"
      ]
    },
    "/tools/rate-card": {
      "filePath": "tools/rate-card/route.jsx",
      "children": [
        "/tools/rate-card/document/",
        "/tools/rate-card/forward/",
        "/tools/rate-card/reverse/"
      ]
    },
    "/tools/reports": {
      "filePath": "tools/reports/route.jsx",
      "children": [
        "/tools/reports/download-reports",
        "/tools/reports/reports-scheduler/"
      ]
    },
    "/add-orders/": {
      "filePath": "add-orders/index.jsx"
    },
    "/home/": {
      "filePath": "home/index.jsx"
    },
    "/tools/": {
      "filePath": "tools/index.jsx"
    },
    "/tools/reports/download-reports": {
      "filePath": "tools/reports/download-reports/route.jsx",
      "parent": "/tools/reports",
      "children": [
        "/tools/reports/download-reports/instant-reports/",
        "/tools/reports/download-reports/scheduled-reports/"
      ]
    },
    "/add-orders/_layout/single-order": {
      "filePath": "add-orders/_layout/single-order.jsx"
    },
    "/settings/api-setups/": {
      "filePath": "settings/api-setups/index.jsx",
      "parent": "/settings"
    },
    "/settings/bank-details/": {
      "filePath": "settings/bank-details/index.jsx",
      "parent": "/settings"
    },
    "/settings/company-details/": {
      "filePath": "settings/company-details/index.jsx",
      "parent": "/settings"
    },
    "/settings/invoice-templates/": {
      "filePath": "settings/invoice-templates/index.jsx",
      "parent": "/settings"
    },
    "/settings/pickup-locations/": {
      "filePath": "settings/pickup-locations/index.jsx",
      "parent": "/settings"
    },
    "/settings/tax-configuration/": {
      "filePath": "settings/tax-configuration/index.jsx",
      "parent": "/settings"
    },
    "/settings/users/": {
      "filePath": "settings/users/index.jsx",
      "parent": "/settings"
    },
    "/tools/activity-logs/": {
      "filePath": "tools/activity-logs/index.jsx"
    },
    "/tools/rate-calculator/domestic/": {
      "filePath": "tools/rate-calculator/domestic/index.jsx",
      "parent": "/tools/rate-calculator"
    },
    "/tools/rate-calculator/international/": {
      "filePath": "tools/rate-calculator/international/index.jsx",
      "parent": "/tools/rate-calculator"
    },
    "/tools/rate-card/document/": {
      "filePath": "tools/rate-card/document/index.jsx",
      "parent": "/tools/rate-card"
    },
    "/tools/rate-card/forward/": {
      "filePath": "tools/rate-card/forward/index.jsx",
      "parent": "/tools/rate-card"
    },
    "/tools/rate-card/reverse/": {
      "filePath": "tools/rate-card/reverse/index.jsx",
      "parent": "/tools/rate-card"
    },
    "/tools/reports/reports-scheduler/": {
      "filePath": "tools/reports/reports-scheduler/index.jsx",
      "parent": "/tools/reports"
    },
    "/tools/reports/download-reports/instant-reports/": {
      "filePath": "tools/reports/download-reports/instant-reports/index.jsx",
      "parent": "/tools/reports/download-reports"
    },
    "/tools/reports/download-reports/scheduled-reports/": {
      "filePath": "tools/reports/download-reports/scheduled-reports/index.lazy.jsx",
      "parent": "/tools/reports/download-reports"
    }
  }
}
ROUTE_MANIFEST_END */
