/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/Login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedToolsIndexImport } from './routes/_authenticated/tools/index'
import { Route as AuthenticatedOrdersIndexImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedHomeIndexImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedToolsReportsRouteImport } from './routes/_authenticated/tools/reports/route'
import { Route as AuthenticatedToolsRateCardRouteImport } from './routes/_authenticated/tools/rate-card/route'
import { Route as AuthenticatedToolsRateCalculatorRouteImport } from './routes/_authenticated/tools/rate-calculator/route'
import { Route as AuthenticatedDashboardInternationalRouteImport } from './routes/_authenticated/dashboard/international/route'
import { Route as AuthenticatedDashboardDomesticRouteImport } from './routes/_authenticated/dashboard/domestic/route'
import { Route as AuthenticatedWarehouseListIndexImport } from './routes/_authenticated/warehouse/list/index'
import { Route as AuthenticatedWarehouseCreateIndexImport } from './routes/_authenticated/warehouse/create/index'
import { Route as AuthenticatedToolsActivityLogsIndexImport } from './routes/_authenticated/tools/activity-logs/index'
import { Route as AuthenticatedSettingsUsersIndexImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsTaxConfigurationIndexImport } from './routes/_authenticated/settings/tax-configuration/index'
import { Route as AuthenticatedSettingsPickupLocationsIndexImport } from './routes/_authenticated/settings/pickup-locations/index'
import { Route as AuthenticatedSettingsInvoiceTemplatesIndexImport } from './routes/_authenticated/settings/invoice-templates/index'
import { Route as AuthenticatedSettingsCompanyDetailsIndexImport } from './routes/_authenticated/settings/company-details/index'
import { Route as AuthenticatedSettingsBankDetailsIndexImport } from './routes/_authenticated/settings/bank-details/index'
import { Route as AuthenticatedSettingsApiSetupsIndexImport } from './routes/_authenticated/settings/api-setups/index'
import { Route as AuthenticatedOrdersCreateIndexImport } from './routes/_authenticated/orders/create/index'
import { Route as AuthenticatedNdrReportsIndexImport } from './routes/_authenticated/ndr/reports/index'
import { Route as AuthenticatedNdrCasesIndexImport } from './routes/_authenticated/ndr/cases/index'
import { Route as AuthenticatedToolsReportsDownloadReportsRouteImport } from './routes/_authenticated/tools/reports/download-reports/route'
import { Route as AuthenticatedToolsReportsReportsSchedulerIndexImport } from './routes/_authenticated/tools/reports/reports-scheduler/index'
import { Route as AuthenticatedToolsRateCardReverseIndexImport } from './routes/_authenticated/tools/rate-card/reverse/index'
import { Route as AuthenticatedToolsRateCardForwardIndexImport } from './routes/_authenticated/tools/rate-card/forward/index'
import { Route as AuthenticatedToolsRateCardDocumentIndexImport } from './routes/_authenticated/tools/rate-card/document/index'
import { Route as AuthenticatedToolsRateCalculatorInternationalIndexImport } from './routes/_authenticated/tools/rate-calculator/international/index'
import { Route as AuthenticatedToolsRateCalculatorDomesticIndexImport } from './routes/_authenticated/tools/rate-calculator/domestic/index'
import { Route as AuthenticatedDashboardInternationalOverviewIndexImport } from './routes/_authenticated/dashboard/international/overview/index'
import { Route as AuthenticatedDashboardDomesticOverviewIndexImport } from './routes/_authenticated/dashboard/domestic/overview/index'
import { Route as AuthenticatedDashboardDomesticOrdersIndexImport } from './routes/_authenticated/dashboard/domestic/orders/index'
import { Route as AuthenticatedToolsReportsDownloadReportsInstantReportsIndexImport } from './routes/_authenticated/tools/reports/download-reports/instant-reports/index'

// Create Virtual Routes

const AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyImport =
  createFileRoute(
    '/_authenticated/tools/reports/download-reports/scheduled-reports/',
  )()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/Login',
  path: '/auth/Login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOrdersIndexRoute = AuthenticatedOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedToolsReportsRouteRoute =
  AuthenticatedToolsReportsRouteImport.update({
    id: '/tools/reports',
    path: '/tools/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedToolsRateCardRouteRoute =
  AuthenticatedToolsRateCardRouteImport.update({
    id: '/tools/rate-card',
    path: '/tools/rate-card',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedToolsRateCalculatorRouteRoute =
  AuthenticatedToolsRateCalculatorRouteImport.update({
    id: '/tools/rate-calculator',
    path: '/tools/rate-calculator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardInternationalRouteRoute =
  AuthenticatedDashboardInternationalRouteImport.update({
    id: '/international',
    path: '/international',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

const AuthenticatedDashboardDomesticRouteRoute =
  AuthenticatedDashboardDomesticRouteImport.update({
    id: '/domestic',
    path: '/domestic',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

const AuthenticatedWarehouseListIndexRoute =
  AuthenticatedWarehouseListIndexImport.update({
    id: '/warehouse/list/',
    path: '/warehouse/list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedWarehouseCreateIndexRoute =
  AuthenticatedWarehouseCreateIndexImport.update({
    id: '/warehouse/create/',
    path: '/warehouse/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedToolsActivityLogsIndexRoute =
  AuthenticatedToolsActivityLogsIndexImport.update({
    id: '/tools/activity-logs/',
    path: '/tools/activity-logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsTaxConfigurationIndexRoute =
  AuthenticatedSettingsTaxConfigurationIndexImport.update({
    id: '/tax-configuration/',
    path: '/tax-configuration/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsPickupLocationsIndexRoute =
  AuthenticatedSettingsPickupLocationsIndexImport.update({
    id: '/pickup-locations/',
    path: '/pickup-locations/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsInvoiceTemplatesIndexRoute =
  AuthenticatedSettingsInvoiceTemplatesIndexImport.update({
    id: '/invoice-templates/',
    path: '/invoice-templates/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsCompanyDetailsIndexRoute =
  AuthenticatedSettingsCompanyDetailsIndexImport.update({
    id: '/company-details/',
    path: '/company-details/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsBankDetailsIndexRoute =
  AuthenticatedSettingsBankDetailsIndexImport.update({
    id: '/bank-details/',
    path: '/bank-details/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsApiSetupsIndexRoute =
  AuthenticatedSettingsApiSetupsIndexImport.update({
    id: '/api-setups/',
    path: '/api-setups/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedOrdersCreateIndexRoute =
  AuthenticatedOrdersCreateIndexImport.update({
    id: '/orders/create/',
    path: '/orders/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedNdrReportsIndexRoute =
  AuthenticatedNdrReportsIndexImport.update({
    id: '/ndr/reports/',
    path: '/ndr/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedNdrCasesIndexRoute = AuthenticatedNdrCasesIndexImport.update(
  {
    id: '/ndr/cases/',
    path: '/ndr/cases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedToolsReportsDownloadReportsRouteRoute =
  AuthenticatedToolsReportsDownloadReportsRouteImport.update({
    id: '/download-reports',
    path: '/download-reports',
    getParentRoute: () => AuthenticatedToolsReportsRouteRoute,
  } as any)

const AuthenticatedToolsReportsReportsSchedulerIndexRoute =
  AuthenticatedToolsReportsReportsSchedulerIndexImport.update({
    id: '/reports-scheduler/',
    path: '/reports-scheduler/',
    getParentRoute: () => AuthenticatedToolsReportsRouteRoute,
  } as any)

const AuthenticatedToolsRateCardReverseIndexRoute =
  AuthenticatedToolsRateCardReverseIndexImport.update({
    id: '/reverse/',
    path: '/reverse/',
    getParentRoute: () => AuthenticatedToolsRateCardRouteRoute,
  } as any)

const AuthenticatedToolsRateCardForwardIndexRoute =
  AuthenticatedToolsRateCardForwardIndexImport.update({
    id: '/forward/',
    path: '/forward/',
    getParentRoute: () => AuthenticatedToolsRateCardRouteRoute,
  } as any)

const AuthenticatedToolsRateCardDocumentIndexRoute =
  AuthenticatedToolsRateCardDocumentIndexImport.update({
    id: '/document/',
    path: '/document/',
    getParentRoute: () => AuthenticatedToolsRateCardRouteRoute,
  } as any)

const AuthenticatedToolsRateCalculatorInternationalIndexRoute =
  AuthenticatedToolsRateCalculatorInternationalIndexImport.update({
    id: '/international/',
    path: '/international/',
    getParentRoute: () => AuthenticatedToolsRateCalculatorRouteRoute,
  } as any)

const AuthenticatedToolsRateCalculatorDomesticIndexRoute =
  AuthenticatedToolsRateCalculatorDomesticIndexImport.update({
    id: '/domestic/',
    path: '/domestic/',
    getParentRoute: () => AuthenticatedToolsRateCalculatorRouteRoute,
  } as any)

const AuthenticatedDashboardInternationalOverviewIndexRoute =
  AuthenticatedDashboardInternationalOverviewIndexImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedDashboardInternationalRouteRoute,
  } as any)

const AuthenticatedDashboardDomesticOverviewIndexRoute =
  AuthenticatedDashboardDomesticOverviewIndexImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedDashboardDomesticRouteRoute,
  } as any)

const AuthenticatedDashboardDomesticOrdersIndexRoute =
  AuthenticatedDashboardDomesticOrdersIndexImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedDashboardDomesticRouteRoute,
  } as any)

const AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute =
  AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyImport.update(
    {
      id: '/scheduled-reports/',
      path: '/scheduled-reports/',
      getParentRoute: () => AuthenticatedToolsReportsDownloadReportsRouteRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_authenticated/tools/reports/download-reports/scheduled-reports/index.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute =
  AuthenticatedToolsReportsDownloadReportsInstantReportsIndexImport.update({
    id: '/instant-reports/',
    path: '/instant-reports/',
    getParentRoute: () => AuthenticatedToolsReportsDownloadReportsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/Login': {
      id: '/auth/Login'
      path: '/auth/Login'
      fullPath: '/auth/Login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard/domestic': {
      id: '/_authenticated/dashboard/domestic'
      path: '/domestic'
      fullPath: '/dashboard/domestic'
      preLoaderRoute: typeof AuthenticatedDashboardDomesticRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteImport
    }
    '/_authenticated/dashboard/international': {
      id: '/_authenticated/dashboard/international'
      path: '/international'
      fullPath: '/dashboard/international'
      preLoaderRoute: typeof AuthenticatedDashboardInternationalRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteImport
    }
    '/_authenticated/tools/rate-calculator': {
      id: '/_authenticated/tools/rate-calculator'
      path: '/tools/rate-calculator'
      fullPath: '/tools/rate-calculator'
      preLoaderRoute: typeof AuthenticatedToolsRateCalculatorRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tools/rate-card': {
      id: '/_authenticated/tools/rate-card'
      path: '/tools/rate-card'
      fullPath: '/tools/rate-card'
      preLoaderRoute: typeof AuthenticatedToolsRateCardRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tools/reports': {
      id: '/_authenticated/tools/reports'
      path: '/tools/reports'
      fullPath: '/tools/reports'
      preLoaderRoute: typeof AuthenticatedToolsReportsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tools/reports/download-reports': {
      id: '/_authenticated/tools/reports/download-reports'
      path: '/download-reports'
      fullPath: '/tools/reports/download-reports'
      preLoaderRoute: typeof AuthenticatedToolsReportsDownloadReportsRouteImport
      parentRoute: typeof AuthenticatedToolsReportsRouteImport
    }
    '/_authenticated/ndr/cases/': {
      id: '/_authenticated/ndr/cases/'
      path: '/ndr/cases'
      fullPath: '/ndr/cases'
      preLoaderRoute: typeof AuthenticatedNdrCasesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/ndr/reports/': {
      id: '/_authenticated/ndr/reports/'
      path: '/ndr/reports'
      fullPath: '/ndr/reports'
      preLoaderRoute: typeof AuthenticatedNdrReportsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders/create/': {
      id: '/_authenticated/orders/create/'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof AuthenticatedOrdersCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/api-setups/': {
      id: '/_authenticated/settings/api-setups/'
      path: '/api-setups'
      fullPath: '/settings/api-setups'
      preLoaderRoute: typeof AuthenticatedSettingsApiSetupsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/bank-details/': {
      id: '/_authenticated/settings/bank-details/'
      path: '/bank-details'
      fullPath: '/settings/bank-details'
      preLoaderRoute: typeof AuthenticatedSettingsBankDetailsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/company-details/': {
      id: '/_authenticated/settings/company-details/'
      path: '/company-details'
      fullPath: '/settings/company-details'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyDetailsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/invoice-templates/': {
      id: '/_authenticated/settings/invoice-templates/'
      path: '/invoice-templates'
      fullPath: '/settings/invoice-templates'
      preLoaderRoute: typeof AuthenticatedSettingsInvoiceTemplatesIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/pickup-locations/': {
      id: '/_authenticated/settings/pickup-locations/'
      path: '/pickup-locations'
      fullPath: '/settings/pickup-locations'
      preLoaderRoute: typeof AuthenticatedSettingsPickupLocationsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/tax-configuration/': {
      id: '/_authenticated/settings/tax-configuration/'
      path: '/tax-configuration'
      fullPath: '/settings/tax-configuration'
      preLoaderRoute: typeof AuthenticatedSettingsTaxConfigurationIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tools/activity-logs/': {
      id: '/_authenticated/tools/activity-logs/'
      path: '/tools/activity-logs'
      fullPath: '/tools/activity-logs'
      preLoaderRoute: typeof AuthenticatedToolsActivityLogsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/warehouse/create/': {
      id: '/_authenticated/warehouse/create/'
      path: '/warehouse/create'
      fullPath: '/warehouse/create'
      preLoaderRoute: typeof AuthenticatedWarehouseCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/warehouse/list/': {
      id: '/_authenticated/warehouse/list/'
      path: '/warehouse/list'
      fullPath: '/warehouse/list'
      preLoaderRoute: typeof AuthenticatedWarehouseListIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/domestic/orders/': {
      id: '/_authenticated/dashboard/domestic/orders/'
      path: '/orders'
      fullPath: '/dashboard/domestic/orders'
      preLoaderRoute: typeof AuthenticatedDashboardDomesticOrdersIndexImport
      parentRoute: typeof AuthenticatedDashboardDomesticRouteImport
    }
    '/_authenticated/dashboard/domestic/overview/': {
      id: '/_authenticated/dashboard/domestic/overview/'
      path: '/overview'
      fullPath: '/dashboard/domestic/overview'
      preLoaderRoute: typeof AuthenticatedDashboardDomesticOverviewIndexImport
      parentRoute: typeof AuthenticatedDashboardDomesticRouteImport
    }
    '/_authenticated/dashboard/international/overview/': {
      id: '/_authenticated/dashboard/international/overview/'
      path: '/overview'
      fullPath: '/dashboard/international/overview'
      preLoaderRoute: typeof AuthenticatedDashboardInternationalOverviewIndexImport
      parentRoute: typeof AuthenticatedDashboardInternationalRouteImport
    }
    '/_authenticated/tools/rate-calculator/domestic/': {
      id: '/_authenticated/tools/rate-calculator/domestic/'
      path: '/domestic'
      fullPath: '/tools/rate-calculator/domestic'
      preLoaderRoute: typeof AuthenticatedToolsRateCalculatorDomesticIndexImport
      parentRoute: typeof AuthenticatedToolsRateCalculatorRouteImport
    }
    '/_authenticated/tools/rate-calculator/international/': {
      id: '/_authenticated/tools/rate-calculator/international/'
      path: '/international'
      fullPath: '/tools/rate-calculator/international'
      preLoaderRoute: typeof AuthenticatedToolsRateCalculatorInternationalIndexImport
      parentRoute: typeof AuthenticatedToolsRateCalculatorRouteImport
    }
    '/_authenticated/tools/rate-card/document/': {
      id: '/_authenticated/tools/rate-card/document/'
      path: '/document'
      fullPath: '/tools/rate-card/document'
      preLoaderRoute: typeof AuthenticatedToolsRateCardDocumentIndexImport
      parentRoute: typeof AuthenticatedToolsRateCardRouteImport
    }
    '/_authenticated/tools/rate-card/forward/': {
      id: '/_authenticated/tools/rate-card/forward/'
      path: '/forward'
      fullPath: '/tools/rate-card/forward'
      preLoaderRoute: typeof AuthenticatedToolsRateCardForwardIndexImport
      parentRoute: typeof AuthenticatedToolsRateCardRouteImport
    }
    '/_authenticated/tools/rate-card/reverse/': {
      id: '/_authenticated/tools/rate-card/reverse/'
      path: '/reverse'
      fullPath: '/tools/rate-card/reverse'
      preLoaderRoute: typeof AuthenticatedToolsRateCardReverseIndexImport
      parentRoute: typeof AuthenticatedToolsRateCardRouteImport
    }
    '/_authenticated/tools/reports/reports-scheduler/': {
      id: '/_authenticated/tools/reports/reports-scheduler/'
      path: '/reports-scheduler'
      fullPath: '/tools/reports/reports-scheduler'
      preLoaderRoute: typeof AuthenticatedToolsReportsReportsSchedulerIndexImport
      parentRoute: typeof AuthenticatedToolsReportsRouteImport
    }
    '/_authenticated/tools/reports/download-reports/instant-reports/': {
      id: '/_authenticated/tools/reports/download-reports/instant-reports/'
      path: '/instant-reports'
      fullPath: '/tools/reports/download-reports/instant-reports'
      preLoaderRoute: typeof AuthenticatedToolsReportsDownloadReportsInstantReportsIndexImport
      parentRoute: typeof AuthenticatedToolsReportsDownloadReportsRouteImport
    }
    '/_authenticated/tools/reports/download-reports/scheduled-reports/': {
      id: '/_authenticated/tools/reports/download-reports/scheduled-reports/'
      path: '/scheduled-reports'
      fullPath: '/tools/reports/download-reports/scheduled-reports'
      preLoaderRoute: typeof AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyImport
      parentRoute: typeof AuthenticatedToolsReportsDownloadReportsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardDomesticRouteRouteChildren {
  AuthenticatedDashboardDomesticOrdersIndexRoute: typeof AuthenticatedDashboardDomesticOrdersIndexRoute
  AuthenticatedDashboardDomesticOverviewIndexRoute: typeof AuthenticatedDashboardDomesticOverviewIndexRoute
}

const AuthenticatedDashboardDomesticRouteRouteChildren: AuthenticatedDashboardDomesticRouteRouteChildren =
  {
    AuthenticatedDashboardDomesticOrdersIndexRoute:
      AuthenticatedDashboardDomesticOrdersIndexRoute,
    AuthenticatedDashboardDomesticOverviewIndexRoute:
      AuthenticatedDashboardDomesticOverviewIndexRoute,
  }

const AuthenticatedDashboardDomesticRouteRouteWithChildren =
  AuthenticatedDashboardDomesticRouteRoute._addFileChildren(
    AuthenticatedDashboardDomesticRouteRouteChildren,
  )

interface AuthenticatedDashboardInternationalRouteRouteChildren {
  AuthenticatedDashboardInternationalOverviewIndexRoute: typeof AuthenticatedDashboardInternationalOverviewIndexRoute
}

const AuthenticatedDashboardInternationalRouteRouteChildren: AuthenticatedDashboardInternationalRouteRouteChildren =
  {
    AuthenticatedDashboardInternationalOverviewIndexRoute:
      AuthenticatedDashboardInternationalOverviewIndexRoute,
  }

const AuthenticatedDashboardInternationalRouteRouteWithChildren =
  AuthenticatedDashboardInternationalRouteRoute._addFileChildren(
    AuthenticatedDashboardInternationalRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardDomesticRouteRoute: typeof AuthenticatedDashboardDomesticRouteRouteWithChildren
  AuthenticatedDashboardInternationalRouteRoute: typeof AuthenticatedDashboardInternationalRouteRouteWithChildren
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardDomesticRouteRoute:
      AuthenticatedDashboardDomesticRouteRouteWithChildren,
    AuthenticatedDashboardInternationalRouteRoute:
      AuthenticatedDashboardInternationalRouteRouteWithChildren,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsApiSetupsIndexRoute: typeof AuthenticatedSettingsApiSetupsIndexRoute
  AuthenticatedSettingsBankDetailsIndexRoute: typeof AuthenticatedSettingsBankDetailsIndexRoute
  AuthenticatedSettingsCompanyDetailsIndexRoute: typeof AuthenticatedSettingsCompanyDetailsIndexRoute
  AuthenticatedSettingsInvoiceTemplatesIndexRoute: typeof AuthenticatedSettingsInvoiceTemplatesIndexRoute
  AuthenticatedSettingsPickupLocationsIndexRoute: typeof AuthenticatedSettingsPickupLocationsIndexRoute
  AuthenticatedSettingsTaxConfigurationIndexRoute: typeof AuthenticatedSettingsTaxConfigurationIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsApiSetupsIndexRoute:
      AuthenticatedSettingsApiSetupsIndexRoute,
    AuthenticatedSettingsBankDetailsIndexRoute:
      AuthenticatedSettingsBankDetailsIndexRoute,
    AuthenticatedSettingsCompanyDetailsIndexRoute:
      AuthenticatedSettingsCompanyDetailsIndexRoute,
    AuthenticatedSettingsInvoiceTemplatesIndexRoute:
      AuthenticatedSettingsInvoiceTemplatesIndexRoute,
    AuthenticatedSettingsPickupLocationsIndexRoute:
      AuthenticatedSettingsPickupLocationsIndexRoute,
    AuthenticatedSettingsTaxConfigurationIndexRoute:
      AuthenticatedSettingsTaxConfigurationIndexRoute,
    AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedToolsRateCalculatorRouteRouteChildren {
  AuthenticatedToolsRateCalculatorDomesticIndexRoute: typeof AuthenticatedToolsRateCalculatorDomesticIndexRoute
  AuthenticatedToolsRateCalculatorInternationalIndexRoute: typeof AuthenticatedToolsRateCalculatorInternationalIndexRoute
}

const AuthenticatedToolsRateCalculatorRouteRouteChildren: AuthenticatedToolsRateCalculatorRouteRouteChildren =
  {
    AuthenticatedToolsRateCalculatorDomesticIndexRoute:
      AuthenticatedToolsRateCalculatorDomesticIndexRoute,
    AuthenticatedToolsRateCalculatorInternationalIndexRoute:
      AuthenticatedToolsRateCalculatorInternationalIndexRoute,
  }

const AuthenticatedToolsRateCalculatorRouteRouteWithChildren =
  AuthenticatedToolsRateCalculatorRouteRoute._addFileChildren(
    AuthenticatedToolsRateCalculatorRouteRouteChildren,
  )

interface AuthenticatedToolsRateCardRouteRouteChildren {
  AuthenticatedToolsRateCardDocumentIndexRoute: typeof AuthenticatedToolsRateCardDocumentIndexRoute
  AuthenticatedToolsRateCardForwardIndexRoute: typeof AuthenticatedToolsRateCardForwardIndexRoute
  AuthenticatedToolsRateCardReverseIndexRoute: typeof AuthenticatedToolsRateCardReverseIndexRoute
}

const AuthenticatedToolsRateCardRouteRouteChildren: AuthenticatedToolsRateCardRouteRouteChildren =
  {
    AuthenticatedToolsRateCardDocumentIndexRoute:
      AuthenticatedToolsRateCardDocumentIndexRoute,
    AuthenticatedToolsRateCardForwardIndexRoute:
      AuthenticatedToolsRateCardForwardIndexRoute,
    AuthenticatedToolsRateCardReverseIndexRoute:
      AuthenticatedToolsRateCardReverseIndexRoute,
  }

const AuthenticatedToolsRateCardRouteRouteWithChildren =
  AuthenticatedToolsRateCardRouteRoute._addFileChildren(
    AuthenticatedToolsRateCardRouteRouteChildren,
  )

interface AuthenticatedToolsReportsDownloadReportsRouteRouteChildren {
  AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute: typeof AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute
  AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute: typeof AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

const AuthenticatedToolsReportsDownloadReportsRouteRouteChildren: AuthenticatedToolsReportsDownloadReportsRouteRouteChildren =
  {
    AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute:
      AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute,
    AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute:
      AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute,
  }

const AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren =
  AuthenticatedToolsReportsDownloadReportsRouteRoute._addFileChildren(
    AuthenticatedToolsReportsDownloadReportsRouteRouteChildren,
  )

interface AuthenticatedToolsReportsRouteRouteChildren {
  AuthenticatedToolsReportsDownloadReportsRouteRoute: typeof AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren
  AuthenticatedToolsReportsReportsSchedulerIndexRoute: typeof AuthenticatedToolsReportsReportsSchedulerIndexRoute
}

const AuthenticatedToolsReportsRouteRouteChildren: AuthenticatedToolsReportsRouteRouteChildren =
  {
    AuthenticatedToolsReportsDownloadReportsRouteRoute:
      AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren,
    AuthenticatedToolsReportsReportsSchedulerIndexRoute:
      AuthenticatedToolsReportsReportsSchedulerIndexRoute,
  }

const AuthenticatedToolsReportsRouteRouteWithChildren =
  AuthenticatedToolsReportsRouteRoute._addFileChildren(
    AuthenticatedToolsReportsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedToolsRateCalculatorRouteRoute: typeof AuthenticatedToolsRateCalculatorRouteRouteWithChildren
  AuthenticatedToolsRateCardRouteRoute: typeof AuthenticatedToolsRateCardRouteRouteWithChildren
  AuthenticatedToolsReportsRouteRoute: typeof AuthenticatedToolsReportsRouteRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedNdrCasesIndexRoute: typeof AuthenticatedNdrCasesIndexRoute
  AuthenticatedNdrReportsIndexRoute: typeof AuthenticatedNdrReportsIndexRoute
  AuthenticatedOrdersCreateIndexRoute: typeof AuthenticatedOrdersCreateIndexRoute
  AuthenticatedToolsActivityLogsIndexRoute: typeof AuthenticatedToolsActivityLogsIndexRoute
  AuthenticatedWarehouseCreateIndexRoute: typeof AuthenticatedWarehouseCreateIndexRoute
  AuthenticatedWarehouseListIndexRoute: typeof AuthenticatedWarehouseListIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedToolsRateCalculatorRouteRoute:
    AuthenticatedToolsRateCalculatorRouteRouteWithChildren,
  AuthenticatedToolsRateCardRouteRoute:
    AuthenticatedToolsRateCardRouteRouteWithChildren,
  AuthenticatedToolsReportsRouteRoute:
    AuthenticatedToolsReportsRouteRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedNdrCasesIndexRoute: AuthenticatedNdrCasesIndexRoute,
  AuthenticatedNdrReportsIndexRoute: AuthenticatedNdrReportsIndexRoute,
  AuthenticatedOrdersCreateIndexRoute: AuthenticatedOrdersCreateIndexRoute,
  AuthenticatedToolsActivityLogsIndexRoute:
    AuthenticatedToolsActivityLogsIndexRoute,
  AuthenticatedWarehouseCreateIndexRoute:
    AuthenticatedWarehouseCreateIndexRoute,
  AuthenticatedWarehouseListIndexRoute: AuthenticatedWarehouseListIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/Login': typeof AuthLoginRoute
  '/dashboard/domestic': typeof AuthenticatedDashboardDomesticRouteRouteWithChildren
  '/dashboard/international': typeof AuthenticatedDashboardInternationalRouteRouteWithChildren
  '/tools/rate-calculator': typeof AuthenticatedToolsRateCalculatorRouteRouteWithChildren
  '/tools/rate-card': typeof AuthenticatedToolsRateCardRouteRouteWithChildren
  '/tools/reports': typeof AuthenticatedToolsReportsRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/tools/reports/download-reports': typeof AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren
  '/ndr/cases': typeof AuthenticatedNdrCasesIndexRoute
  '/ndr/reports': typeof AuthenticatedNdrReportsIndexRoute
  '/orders/create': typeof AuthenticatedOrdersCreateIndexRoute
  '/settings/api-setups': typeof AuthenticatedSettingsApiSetupsIndexRoute
  '/settings/bank-details': typeof AuthenticatedSettingsBankDetailsIndexRoute
  '/settings/company-details': typeof AuthenticatedSettingsCompanyDetailsIndexRoute
  '/settings/invoice-templates': typeof AuthenticatedSettingsInvoiceTemplatesIndexRoute
  '/settings/pickup-locations': typeof AuthenticatedSettingsPickupLocationsIndexRoute
  '/settings/tax-configuration': typeof AuthenticatedSettingsTaxConfigurationIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/tools/activity-logs': typeof AuthenticatedToolsActivityLogsIndexRoute
  '/warehouse/create': typeof AuthenticatedWarehouseCreateIndexRoute
  '/warehouse/list': typeof AuthenticatedWarehouseListIndexRoute
  '/dashboard/domestic/orders': typeof AuthenticatedDashboardDomesticOrdersIndexRoute
  '/dashboard/domestic/overview': typeof AuthenticatedDashboardDomesticOverviewIndexRoute
  '/dashboard/international/overview': typeof AuthenticatedDashboardInternationalOverviewIndexRoute
  '/tools/rate-calculator/domestic': typeof AuthenticatedToolsRateCalculatorDomesticIndexRoute
  '/tools/rate-calculator/international': typeof AuthenticatedToolsRateCalculatorInternationalIndexRoute
  '/tools/rate-card/document': typeof AuthenticatedToolsRateCardDocumentIndexRoute
  '/tools/rate-card/forward': typeof AuthenticatedToolsRateCardForwardIndexRoute
  '/tools/rate-card/reverse': typeof AuthenticatedToolsRateCardReverseIndexRoute
  '/tools/reports/reports-scheduler': typeof AuthenticatedToolsReportsReportsSchedulerIndexRoute
  '/tools/reports/download-reports/instant-reports': typeof AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute
  '/tools/reports/download-reports/scheduled-reports': typeof AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/Login': typeof AuthLoginRoute
  '/dashboard/domestic': typeof AuthenticatedDashboardDomesticRouteRouteWithChildren
  '/dashboard/international': typeof AuthenticatedDashboardInternationalRouteRouteWithChildren
  '/tools/rate-calculator': typeof AuthenticatedToolsRateCalculatorRouteRouteWithChildren
  '/tools/rate-card': typeof AuthenticatedToolsRateCardRouteRouteWithChildren
  '/tools/reports': typeof AuthenticatedToolsReportsRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/tools/reports/download-reports': typeof AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren
  '/ndr/cases': typeof AuthenticatedNdrCasesIndexRoute
  '/ndr/reports': typeof AuthenticatedNdrReportsIndexRoute
  '/orders/create': typeof AuthenticatedOrdersCreateIndexRoute
  '/settings/api-setups': typeof AuthenticatedSettingsApiSetupsIndexRoute
  '/settings/bank-details': typeof AuthenticatedSettingsBankDetailsIndexRoute
  '/settings/company-details': typeof AuthenticatedSettingsCompanyDetailsIndexRoute
  '/settings/invoice-templates': typeof AuthenticatedSettingsInvoiceTemplatesIndexRoute
  '/settings/pickup-locations': typeof AuthenticatedSettingsPickupLocationsIndexRoute
  '/settings/tax-configuration': typeof AuthenticatedSettingsTaxConfigurationIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/tools/activity-logs': typeof AuthenticatedToolsActivityLogsIndexRoute
  '/warehouse/create': typeof AuthenticatedWarehouseCreateIndexRoute
  '/warehouse/list': typeof AuthenticatedWarehouseListIndexRoute
  '/dashboard/domestic/orders': typeof AuthenticatedDashboardDomesticOrdersIndexRoute
  '/dashboard/domestic/overview': typeof AuthenticatedDashboardDomesticOverviewIndexRoute
  '/dashboard/international/overview': typeof AuthenticatedDashboardInternationalOverviewIndexRoute
  '/tools/rate-calculator/domestic': typeof AuthenticatedToolsRateCalculatorDomesticIndexRoute
  '/tools/rate-calculator/international': typeof AuthenticatedToolsRateCalculatorInternationalIndexRoute
  '/tools/rate-card/document': typeof AuthenticatedToolsRateCardDocumentIndexRoute
  '/tools/rate-card/forward': typeof AuthenticatedToolsRateCardForwardIndexRoute
  '/tools/rate-card/reverse': typeof AuthenticatedToolsRateCardReverseIndexRoute
  '/tools/reports/reports-scheduler': typeof AuthenticatedToolsReportsReportsSchedulerIndexRoute
  '/tools/reports/download-reports/instant-reports': typeof AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute
  '/tools/reports/download-reports/scheduled-reports': typeof AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/Login': typeof AuthLoginRoute
  '/_authenticated/dashboard/domestic': typeof AuthenticatedDashboardDomesticRouteRouteWithChildren
  '/_authenticated/dashboard/international': typeof AuthenticatedDashboardInternationalRouteRouteWithChildren
  '/_authenticated/tools/rate-calculator': typeof AuthenticatedToolsRateCalculatorRouteRouteWithChildren
  '/_authenticated/tools/rate-card': typeof AuthenticatedToolsRateCardRouteRouteWithChildren
  '/_authenticated/tools/reports': typeof AuthenticatedToolsReportsRouteRouteWithChildren
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/tools/reports/download-reports': typeof AuthenticatedToolsReportsDownloadReportsRouteRouteWithChildren
  '/_authenticated/ndr/cases/': typeof AuthenticatedNdrCasesIndexRoute
  '/_authenticated/ndr/reports/': typeof AuthenticatedNdrReportsIndexRoute
  '/_authenticated/orders/create/': typeof AuthenticatedOrdersCreateIndexRoute
  '/_authenticated/settings/api-setups/': typeof AuthenticatedSettingsApiSetupsIndexRoute
  '/_authenticated/settings/bank-details/': typeof AuthenticatedSettingsBankDetailsIndexRoute
  '/_authenticated/settings/company-details/': typeof AuthenticatedSettingsCompanyDetailsIndexRoute
  '/_authenticated/settings/invoice-templates/': typeof AuthenticatedSettingsInvoiceTemplatesIndexRoute
  '/_authenticated/settings/pickup-locations/': typeof AuthenticatedSettingsPickupLocationsIndexRoute
  '/_authenticated/settings/tax-configuration/': typeof AuthenticatedSettingsTaxConfigurationIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/tools/activity-logs/': typeof AuthenticatedToolsActivityLogsIndexRoute
  '/_authenticated/warehouse/create/': typeof AuthenticatedWarehouseCreateIndexRoute
  '/_authenticated/warehouse/list/': typeof AuthenticatedWarehouseListIndexRoute
  '/_authenticated/dashboard/domestic/orders/': typeof AuthenticatedDashboardDomesticOrdersIndexRoute
  '/_authenticated/dashboard/domestic/overview/': typeof AuthenticatedDashboardDomesticOverviewIndexRoute
  '/_authenticated/dashboard/international/overview/': typeof AuthenticatedDashboardInternationalOverviewIndexRoute
  '/_authenticated/tools/rate-calculator/domestic/': typeof AuthenticatedToolsRateCalculatorDomesticIndexRoute
  '/_authenticated/tools/rate-calculator/international/': typeof AuthenticatedToolsRateCalculatorInternationalIndexRoute
  '/_authenticated/tools/rate-card/document/': typeof AuthenticatedToolsRateCardDocumentIndexRoute
  '/_authenticated/tools/rate-card/forward/': typeof AuthenticatedToolsRateCardForwardIndexRoute
  '/_authenticated/tools/rate-card/reverse/': typeof AuthenticatedToolsRateCardReverseIndexRoute
  '/_authenticated/tools/reports/reports-scheduler/': typeof AuthenticatedToolsReportsReportsSchedulerIndexRoute
  '/_authenticated/tools/reports/download-reports/instant-reports/': typeof AuthenticatedToolsReportsDownloadReportsInstantReportsIndexRoute
  '/_authenticated/tools/reports/download-reports/scheduled-reports/': typeof AuthenticatedToolsReportsDownloadReportsScheduledReportsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/dashboard'
    | '/settings'
    | '/auth/Login'
    | '/dashboard/domestic'
    | '/dashboard/international'
    | '/tools/rate-calculator'
    | '/tools/rate-card'
    | '/tools/reports'
    | '/home'
    | '/orders'
    | '/tools'
    | '/tools/reports/download-reports'
    | '/ndr/cases'
    | '/ndr/reports'
    | '/orders/create'
    | '/settings/api-setups'
    | '/settings/bank-details'
    | '/settings/company-details'
    | '/settings/invoice-templates'
    | '/settings/pickup-locations'
    | '/settings/tax-configuration'
    | '/settings/users'
    | '/tools/activity-logs'
    | '/warehouse/create'
    | '/warehouse/list'
    | '/dashboard/domestic/orders'
    | '/dashboard/domestic/overview'
    | '/dashboard/international/overview'
    | '/tools/rate-calculator/domestic'
    | '/tools/rate-calculator/international'
    | '/tools/rate-card/document'
    | '/tools/rate-card/forward'
    | '/tools/rate-card/reverse'
    | '/tools/reports/reports-scheduler'
    | '/tools/reports/download-reports/instant-reports'
    | '/tools/reports/download-reports/scheduled-reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/dashboard'
    | '/settings'
    | '/auth/Login'
    | '/dashboard/domestic'
    | '/dashboard/international'
    | '/tools/rate-calculator'
    | '/tools/rate-card'
    | '/tools/reports'
    | '/home'
    | '/orders'
    | '/tools'
    | '/tools/reports/download-reports'
    | '/ndr/cases'
    | '/ndr/reports'
    | '/orders/create'
    | '/settings/api-setups'
    | '/settings/bank-details'
    | '/settings/company-details'
    | '/settings/invoice-templates'
    | '/settings/pickup-locations'
    | '/settings/tax-configuration'
    | '/settings/users'
    | '/tools/activity-logs'
    | '/warehouse/create'
    | '/warehouse/list'
    | '/dashboard/domestic/orders'
    | '/dashboard/domestic/overview'
    | '/dashboard/international/overview'
    | '/tools/rate-calculator/domestic'
    | '/tools/rate-calculator/international'
    | '/tools/rate-card/document'
    | '/tools/rate-card/forward'
    | '/tools/rate-card/reverse'
    | '/tools/reports/reports-scheduler'
    | '/tools/reports/download-reports/instant-reports'
    | '/tools/reports/download-reports/scheduled-reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/auth/Login'
    | '/_authenticated/dashboard/domestic'
    | '/_authenticated/dashboard/international'
    | '/_authenticated/tools/rate-calculator'
    | '/_authenticated/tools/rate-card'
    | '/_authenticated/tools/reports'
    | '/_authenticated/home/'
    | '/_authenticated/orders/'
    | '/_authenticated/tools/'
    | '/_authenticated/tools/reports/download-reports'
    | '/_authenticated/ndr/cases/'
    | '/_authenticated/ndr/reports/'
    | '/_authenticated/orders/create/'
    | '/_authenticated/settings/api-setups/'
    | '/_authenticated/settings/bank-details/'
    | '/_authenticated/settings/company-details/'
    | '/_authenticated/settings/invoice-templates/'
    | '/_authenticated/settings/pickup-locations/'
    | '/_authenticated/settings/tax-configuration/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/tools/activity-logs/'
    | '/_authenticated/warehouse/create/'
    | '/_authenticated/warehouse/list/'
    | '/_authenticated/dashboard/domestic/orders/'
    | '/_authenticated/dashboard/domestic/overview/'
    | '/_authenticated/dashboard/international/overview/'
    | '/_authenticated/tools/rate-calculator/domestic/'
    | '/_authenticated/tools/rate-calculator/international/'
    | '/_authenticated/tools/rate-card/document/'
    | '/_authenticated/tools/rate-card/forward/'
    | '/_authenticated/tools/rate-card/reverse/'
    | '/_authenticated/tools/reports/reports-scheduler/'
    | '/_authenticated/tools/reports/download-reports/instant-reports/'
    | '/_authenticated/tools/reports/download-reports/scheduled-reports/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth/Login"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.jsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/settings",
        "/_authenticated/tools/rate-calculator",
        "/_authenticated/tools/rate-card",
        "/_authenticated/tools/reports",
        "/_authenticated/home/",
        "/_authenticated/orders/",
        "/_authenticated/tools/",
        "/_authenticated/ndr/cases/",
        "/_authenticated/ndr/reports/",
        "/_authenticated/orders/create/",
        "/_authenticated/tools/activity-logs/",
        "/_authenticated/warehouse/create/",
        "/_authenticated/warehouse/list/"
      ]
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard/route.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard/domestic",
        "/_authenticated/dashboard/international"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/api-setups/",
        "/_authenticated/settings/bank-details/",
        "/_authenticated/settings/company-details/",
        "/_authenticated/settings/invoice-templates/",
        "/_authenticated/settings/pickup-locations/",
        "/_authenticated/settings/tax-configuration/",
        "/_authenticated/settings/users/"
      ]
    },
    "/auth/Login": {
      "filePath": "auth/Login.jsx"
    },
    "/_authenticated/dashboard/domestic": {
      "filePath": "_authenticated/dashboard/domestic/route.jsx",
      "parent": "/_authenticated/dashboard",
      "children": [
        "/_authenticated/dashboard/domestic/orders/",
        "/_authenticated/dashboard/domestic/overview/"
      ]
    },
    "/_authenticated/dashboard/international": {
      "filePath": "_authenticated/dashboard/international/route.jsx",
      "parent": "/_authenticated/dashboard",
      "children": [
        "/_authenticated/dashboard/international/overview/"
      ]
    },
    "/_authenticated/tools/rate-calculator": {
      "filePath": "_authenticated/tools/rate-calculator/route.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/tools/rate-calculator/domestic/",
        "/_authenticated/tools/rate-calculator/international/"
      ]
    },
    "/_authenticated/tools/rate-card": {
      "filePath": "_authenticated/tools/rate-card/route.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/tools/rate-card/document/",
        "/_authenticated/tools/rate-card/forward/",
        "/_authenticated/tools/rate-card/reverse/"
      ]
    },
    "/_authenticated/tools/reports": {
      "filePath": "_authenticated/tools/reports/route.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/tools/reports/download-reports",
        "/_authenticated/tools/reports/reports-scheduler/"
      ]
    },
    "/_authenticated/home/": {
      "filePath": "_authenticated/home/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/": {
      "filePath": "_authenticated/orders/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tools/": {
      "filePath": "_authenticated/tools/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tools/reports/download-reports": {
      "filePath": "_authenticated/tools/reports/download-reports/route.jsx",
      "parent": "/_authenticated/tools/reports",
      "children": [
        "/_authenticated/tools/reports/download-reports/instant-reports/",
        "/_authenticated/tools/reports/download-reports/scheduled-reports/"
      ]
    },
    "/_authenticated/ndr/cases/": {
      "filePath": "_authenticated/ndr/cases/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ndr/reports/": {
      "filePath": "_authenticated/ndr/reports/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/create/": {
      "filePath": "_authenticated/orders/create/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/api-setups/": {
      "filePath": "_authenticated/settings/api-setups/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/bank-details/": {
      "filePath": "_authenticated/settings/bank-details/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/company-details/": {
      "filePath": "_authenticated/settings/company-details/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/invoice-templates/": {
      "filePath": "_authenticated/settings/invoice-templates/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/pickup-locations/": {
      "filePath": "_authenticated/settings/pickup-locations/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/tax-configuration/": {
      "filePath": "_authenticated/settings/tax-configuration/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/users/": {
      "filePath": "_authenticated/settings/users/index.jsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tools/activity-logs/": {
      "filePath": "_authenticated/tools/activity-logs/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/warehouse/create/": {
      "filePath": "_authenticated/warehouse/create/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/warehouse/list/": {
      "filePath": "_authenticated/warehouse/list/index.jsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/domestic/orders/": {
      "filePath": "_authenticated/dashboard/domestic/orders/index.jsx",
      "parent": "/_authenticated/dashboard/domestic"
    },
    "/_authenticated/dashboard/domestic/overview/": {
      "filePath": "_authenticated/dashboard/domestic/overview/index.jsx",
      "parent": "/_authenticated/dashboard/domestic"
    },
    "/_authenticated/dashboard/international/overview/": {
      "filePath": "_authenticated/dashboard/international/overview/index.jsx",
      "parent": "/_authenticated/dashboard/international"
    },
    "/_authenticated/tools/rate-calculator/domestic/": {
      "filePath": "_authenticated/tools/rate-calculator/domestic/index.jsx",
      "parent": "/_authenticated/tools/rate-calculator"
    },
    "/_authenticated/tools/rate-calculator/international/": {
      "filePath": "_authenticated/tools/rate-calculator/international/index.jsx",
      "parent": "/_authenticated/tools/rate-calculator"
    },
    "/_authenticated/tools/rate-card/document/": {
      "filePath": "_authenticated/tools/rate-card/document/index.jsx",
      "parent": "/_authenticated/tools/rate-card"
    },
    "/_authenticated/tools/rate-card/forward/": {
      "filePath": "_authenticated/tools/rate-card/forward/index.jsx",
      "parent": "/_authenticated/tools/rate-card"
    },
    "/_authenticated/tools/rate-card/reverse/": {
      "filePath": "_authenticated/tools/rate-card/reverse/index.jsx",
      "parent": "/_authenticated/tools/rate-card"
    },
    "/_authenticated/tools/reports/reports-scheduler/": {
      "filePath": "_authenticated/tools/reports/reports-scheduler/index.jsx",
      "parent": "/_authenticated/tools/reports"
    },
    "/_authenticated/tools/reports/download-reports/instant-reports/": {
      "filePath": "_authenticated/tools/reports/download-reports/instant-reports/index.jsx",
      "parent": "/_authenticated/tools/reports/download-reports"
    },
    "/_authenticated/tools/reports/download-reports/scheduled-reports/": {
      "filePath": "_authenticated/tools/reports/download-reports/scheduled-reports/index.lazy.jsx",
      "parent": "/_authenticated/tools/reports/download-reports"
    }
  }
}
ROUTE_MANIFEST_END */
